### ISSUE TITLE
GIF's dont play unless you hover over them.

### ISSUE THREAD

**Issue by MetalRhythm** [bmarian/chat-images#45]
GIF's dont play unless you hover over them. Any way to change that?
![Screenshot 2022-02-06 101217](https://user-images.githubusercontent.com/99132299/152687460-88863e59-a4c2-4c93-902b-479425c157f4.png)

**Comment by Demofly16** [comment]
Its been a long time since you post this, but i recently download this module and found out how to get rid of the freezing gif thing, so i put it here, just if someone runs into this module and have the same issue.

Just go to Modules/Chat images/Scripts/Image-manager And then delete the file named "gif-freez"
When you delete that file, you need to go to the main file and delete the import of that function.

So go to Modules/Chat images/ Scripts and there is a file called "chat-images" 
just enter in the file and the first lines, look that one is called import freezegif or something like that and with that the gifs dont freeze anymore.

Maybe if you just delete the import and the problem is resolved much faster, but i did it that way how i explained and it worked nevertheless.
